name: space-base
recipe: drupal8
proxy:
  solrserver:
    - solr.space-base.lndo.site:8983
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"
  solrserver:
    type: solr:6.6
    portforward: true
    core: drupal
    config:
      conf: .platform/solr-conf
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
config:
  via: nginx
  webroot: web
  database: mariadb:10.1
