name: space-base
recipe: drupal8
proxy:
  mailhog:
    - mail.lemp.lndo.site
  solrserver:
    - solr.space-base.lndo.site:8983
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"
  solrserver:
    type: solr:6.6
    portforward: true
    core: drupal
    config:
      conf: .platform/solr-conf
  mailhog:
    type: mailhog
    hogfrom:
      - appserver    
    portforward: 1026    
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
config:
  via: nginx
  webroot: web
  database: mariadb:10.1
