name: space-base
recipe: drupal8
services:
  appserver:
    build:
      - "curl -sS https://platform.sh/cli/installer | php"
tooling:
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd:
      - /var/www/.platformsh/bin/platform
    options:
      passthrough: true
config:
  via: nginx
  webroot: web
  database: mariadb:10.1
